// Code generated by "stringer -type=AudioCodecs"; DO NOT EDIT.

package segments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Aac-0]
	_ = x[Ac3-1]
	_ = x[Eac3-2]
	_ = x[Mp3-3]
}

const _AudioCodecs_name = "aacac3eac3mp3"

var _AudioCodecs_index = [...]uint8{0, 3, 6, 10, 13}

func (i AudioCodecs) String() string {
	if i < 0 || i >= AudioCodecs(len(_AudioCodecs_index)-1) {
		return "AudioCodecs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AudioCodecs_name[_AudioCodecs_index[i]:_AudioCodecs_index[i+1]]
}
