// Code generated by "stringer -type=MediaType"; DO NOT EDIT.

package segments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Vod-0]
	_ = x[Event-1]
}

const _MediaType_name = "vodevent"

var _MediaType_index = [...]uint8{0, 3, 8}

func (i MediaType) String() string {
	if i < 0 || i >= MediaType(len(_MediaType_index)-1) {
		return "MediaType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MediaType_name[_MediaType_index[i]:_MediaType_index[i+1]]
}
