// Code generated by "stringer -type=VideoProfile"; DO NOT EDIT.

package segments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Main-0]
	_ = x[BaseLine-1]
	_ = x[High-2]
}

const _VideoProfile_name = "mainbaselinehigh"

var _VideoProfile_index = [...]uint8{0, 4, 12, 16}

func (i VideoProfile) String() string {
	if i < 0 || i >= VideoProfile(len(_VideoProfile_index)-1) {
		return "VideoProfile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoProfile_name[_VideoProfile_index[i]:_VideoProfile_index[i+1]]
}
