// Code generated by "stringer -type=VideoCodecs"; DO NOT EDIT.

package segments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[H264-0]
	_ = x[H265-1]
}

const _VideoCodecs_name = "libx264libx265"

var _VideoCodecs_index = [...]uint8{0, 7, 14}

func (i VideoCodecs) String() string {
	if i < 0 || i >= VideoCodecs(len(_VideoCodecs_index)-1) {
		return "VideoCodecs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoCodecs_name[_VideoCodecs_index[i]:_VideoCodecs_index[i+1]]
}
